### ISSUE TITLE
Decision tree classification, Data visualization 

### ISSUE THREAD

**Issue by oj1o1** [SrijanShovit/HealthLearning#3]
Hey @SrijanShovit 
I am GSSOC Contributor .I'll add decision tree classifier in LUNG CANCER DETECTION  ...Can you please assign me

**Comment by MehekFatima** [comment]
Hi @SrijanShovit  ,

I hope this message finds you well. I'm excited to express my interest in contributing to the GSSOC project and would like to request assignment of the issue.

Having reviewed the issue description, I'm confident in my ability to make a meaningful contribution towards resolving it. Could you please confirm if this issue is available for assignment?

I'm looking forward to the opportunity to contribute to the project.

**Comment by SrijanShovit** [comment]
Hi @oj1o1 Let me open up some issues in proper order of workflow till evening, then I will assign accordingly. 

Same goes for you @MehekFatima 
Thanks

**Comment by MehekFatima** [comment]
Okay 👍
